### ISSUE TITLE
Fix reference to FlowRouter

### ISSUE THREAD

**Issue by GeoffreyBooth** [meteor-activeroute/flow-router#3]
https://github.com/meteor-activeroute/flow-router/blob/c005ee7270285ce3992ba9cf9769a1d368188af6/client/activeroute-flow-router.js#L2

should be:

```js
import { FlowRouter } from 'meteor/kadira:flow-router'
```

**Comment by zimme** [comment]
Nice catch, I'll try and have it fixed tonight. Would happily accept a PR too.

**Comment by zimme** [comment]
This should be fixed in `1.0.0-alpha.7`.
